revisao3b/models/users.py
from ..db import get_connection

class User:
    def __init__(self, email, nome):
        self.email = email
        self.nome = nome
        
    def save(self):
        conn = get_connection()
        conn.execute("INSERT INTO users(email, nome) values(?,?)", (self.email, self.nome))
        conn.commit()
        conn.close()
        return True
    
    @classmethod
    def all(cls):
        conn = get_connection()
        users = conn.execute("SELECT * FROM users").fetchall()
        return users

revisao3b/__init__.py
from flask import Flask

app  = Flask(__name__)

revisao3b/app.py
from flask import Flask, render_template, redirect, url_for, request, Blueprint
from .controllers import user_controller
from .controllers import tarefa_controller

app = Flask(__name__)
app.register_blueprint(user_controller.bp)

@app.route('/')
def login():
    return render_template('/users/login.html')

@app.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        # Processar o formulário de cadastro
        # ...
        return redirect(url_for('login'))
    return render_template('/users/register.html')

if __name__ == '__main__':
    app.run(debug=True)

revisao3b/controllers/__init__.py
from . import user_controller

revisao3b/controllers/user_controller.py
from flask import Flask, render_template, redirect, url_for, request, Blueprint
from .. import app
from ..models.users import User

bp = Blueprint('users', __name__, url_prefix='/users')
@bp.route('/login',  methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('users/login.html')

@bp.route('/register',  methods=['GET', 'POST'])
def register():
    return render_template('users/register.html')


revisao3b/db/__init__.py
import sqlite3
import os

DATABASE = 'database.db'
dirname = os.path.dirname(os.path.realpath(__file__))

def get_connection():    
    conn = sqlite3.connect(os.path.join(dirname, DATABASE))
    conn.row_factory = sqlite3.Row
    return conn



revisao3b/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Realizar login</h1>
    <form action="{{url_for('users.login')}}" method="post">
    <input type="email" name="email" placeholder="email">
    <input type="password" name="password" placeholder="senha">
    <button>Enviar</button>
    </form>

    <a href="{{ url_for('register') }}">Fazer cadastro</a>

</body>
</html>

revisao3b/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Cadastro</h1>
    <form action="{{ url_for('register') }}" method="post">
        <input type="text" name="name" placeholder="nome">
        <input type="email" name="email" placeholder="email">
        <input type="password" name="password" placeholder="senha">
        <button type="submit">Enviar</button>
    </form>

    </form>
</body>
</html>